export interface Product {
  id: string
  name: string
  price: number
  originalPrice?: number
  image: string
  category: string
  subcategory: string
  brand: string
  description: string
  tags: string[]
  rating: number
  reviewCount: number
  inStock: boolean
  stockQuantity: number
  storeSection: string
  barcode: string
  nutritionInfo?: {
    calories?: number
    protein?: number
    carbs?: number
    fat?: number
    fiber?: number
    sodium?: number
  }
  allergens?: string[]
  organic?: boolean
  glutenFree?: boolean
  vegan?: boolean
  vegetarian?: boolean
  weight?: string
  dimensions?: string
  createdAt: string
  updatedAt: string
}

// Comprehensive product database
export const PRODUCTS_DATABASE: Product[] = [
  // Produce Section
  {
    id: "prod_001",
    name: "Organic Bananas",
    price: 2.48,
    originalPrice: 2.98,
    image: "🍌",
    category: "Produce",
    subcategory: "Fruits",
    brand: "Organic Valley",
    description: "Fresh organic bananas, perfect for snacking or smoothies",
    tags: ["organic", "fresh", "potassium", "healthy"],
    rating: 4.5,
    reviewCount: 1247,
    inStock: true,
    stockQuantity: 150,
    storeSection: "produce",
    barcode: "1234567890123",
    nutritionInfo: {
      calories: 105,
      protein: 1.3,
      carbs: 27,
      fat: 0.4,
      fiber: 3.1,
      sodium: 1,
    },
    allergens: [],
    organic: true,
    glutenFree: true,
    vegan: true,
    vegetarian: true,
    weight: "1 lb",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_002",
    name: "Fresh Strawberries",
    price: 4.99,
    image: "🍓",
    category: "Produce",
    subcategory: "Berries",
    brand: "Fresh Farms",
    description: "Sweet, juicy strawberries packed with vitamin C",
    tags: ["fresh", "vitamin-c", "antioxidants", "sweet"],
    rating: 4.3,
    reviewCount: 892,
    inStock: true,
    stockQuantity: 75,
    storeSection: "produce",
    barcode: "1234567890124",
    nutritionInfo: {
      calories: 49,
      protein: 1,
      carbs: 12,
      fat: 0.5,
      fiber: 3,
      sodium: 2,
    },
    allergens: [],
    organic: false,
    glutenFree: true,
    vegan: true,
    vegetarian: true,
    weight: "1 lb container",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_003",
    name: "Baby Spinach",
    price: 3.99,
    image: "🥬",
    category: "Produce",
    subcategory: "Leafy Greens",
    brand: "Green Leaf",
    description: "Fresh baby spinach leaves, perfect for salads and cooking",
    tags: ["fresh", "iron", "vitamins", "leafy-green"],
    rating: 4.6,
    reviewCount: 654,
    inStock: true,
    stockQuantity: 120,
    storeSection: "produce",
    barcode: "1234567890125",
    nutritionInfo: {
      calories: 23,
      protein: 2.9,
      carbs: 3.6,
      fat: 0.4,
      fiber: 2.2,
      sodium: 79,
    },
    allergens: [],
    organic: false,
    glutenFree: true,
    vegan: true,
    vegetarian: true,
    weight: "5 oz bag",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_004",
    name: "Roma Tomatoes",
    price: 2.99,
    image: "🍅",
    category: "Produce",
    subcategory: "Vegetables",
    brand: "Farm Fresh",
    description: "Fresh Roma tomatoes, ideal for cooking and sauces",
    tags: ["fresh", "lycopene", "cooking", "versatile"],
    rating: 4.2,
    reviewCount: 543,
    inStock: true,
    stockQuantity: 200,
    storeSection: "produce",
    barcode: "1234567890126",
    nutritionInfo: {
      calories: 18,
      protein: 0.9,
      carbs: 3.9,
      fat: 0.2,
      fiber: 1.2,
      sodium: 5,
    },
    allergens: [],
    organic: false,
    glutenFree: true,
    vegan: true,
    vegetarian: true,
    weight: "1 lb",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },

  // Dairy Section
  {
    id: "prod_005",
    name: "Organic Whole Milk",
    price: 4.99,
    image: "🥛",
    category: "Dairy",
    subcategory: "Milk",
    brand: "Organic Valley",
    description: "Fresh organic whole milk from grass-fed cows",
    tags: ["organic", "whole-milk", "calcium", "protein"],
    rating: 4.8,
    reviewCount: 2156,
    inStock: true,
    stockQuantity: 85,
    storeSection: "dairy",
    barcode: "1234567890127",
    nutritionInfo: {
      calories: 150,
      protein: 8,
      carbs: 12,
      fat: 8,
      fiber: 0,
      sodium: 105,
    },
    allergens: ["milk"],
    organic: true,
    glutenFree: true,
    vegan: false,
    vegetarian: true,
    weight: "1 gallon",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_006",
    name: "Greek Yogurt Plain",
    price: 5.99,
    image: "🥛",
    category: "Dairy",
    subcategory: "Yogurt",
    brand: "Chobani",
    description: "Thick and creamy Greek yogurt with live probiotics",
    tags: ["greek-yogurt", "probiotics", "protein", "low-fat"],
    rating: 4.7,
    reviewCount: 1834,
    inStock: true,
    stockQuantity: 95,
    storeSection: "dairy",
    barcode: "1234567890128",
    nutritionInfo: {
      calories: 100,
      protein: 18,
      carbs: 6,
      fat: 0,
      fiber: 0,
      sodium: 65,
    },
    allergens: ["milk"],
    organic: false,
    glutenFree: true,
    vegan: false,
    vegetarian: true,
    weight: "32 oz",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_007",
    name: "Large Eggs",
    price: 2.99,
    image: "🥚",
    category: "Dairy",
    subcategory: "Eggs",
    brand: "Farm Fresh",
    description: "Grade A large eggs from cage-free hens",
    tags: ["cage-free", "protein", "vitamin-d", "fresh"],
    rating: 4.5,
    reviewCount: 1456,
    inStock: true,
    stockQuantity: 180,
    storeSection: "dairy",
    barcode: "1234567890129",
    nutritionInfo: {
      calories: 70,
      protein: 6,
      carbs: 0,
      fat: 5,
      fiber: 0,
      sodium: 70,
    },
    allergens: ["eggs"],
    organic: false,
    glutenFree: true,
    vegan: false,
    vegetarian: true,
    weight: "12 count",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_008",
    name: "Sharp Cheddar Cheese",
    price: 4.49,
    image: "🧀",
    category: "Dairy",
    subcategory: "Cheese",
    brand: "Tillamook",
    description: "Aged sharp cheddar cheese with rich, bold flavor",
    tags: ["aged", "sharp", "calcium", "protein"],
    rating: 4.6,
    reviewCount: 987,
    inStock: true,
    stockQuantity: 65,
    storeSection: "dairy",
    barcode: "1234567890130",
    nutritionInfo: {
      calories: 110,
      protein: 7,
      carbs: 1,
      fat: 9,
      fiber: 0,
      sodium: 180,
    },
    allergens: ["milk"],
    organic: false,
    glutenFree: true,
    vegan: false,
    vegetarian: true,
    weight: "8 oz block",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },

  // Meat & Seafood Section
  {
    id: "prod_009",
    name: "Boneless Chicken Breast",
    price: 8.99,
    image: "🍗",
    category: "Meat",
    subcategory: "Poultry",
    brand: "Perdue",
    description: "Fresh boneless, skinless chicken breast",
    tags: ["fresh", "lean-protein", "boneless", "skinless"],
    rating: 4.4,
    reviewCount: 1234,
    inStock: true,
    stockQuantity: 45,
    storeSection: "meat",
    barcode: "1234567890131",
    nutritionInfo: {
      calories: 165,
      protein: 31,
      carbs: 0,
      fat: 3.6,
      fiber: 0,
      sodium: 74,
    },
    allergens: [],
    organic: false,
    glutenFree: true,
    vegan: false,
    vegetarian: false,
    weight: "1 lb",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_010",
    name: "Ground Beef 80/20",
    price: 6.99,
    image: "🥩",
    category: "Meat",
    subcategory: "Beef",
    brand: "Angus Select",
    description: "Fresh ground beef, 80% lean, 20% fat",
    tags: ["fresh", "ground-beef", "protein", "versatile"],
    rating: 4.3,
    reviewCount: 876,
    inStock: true,
    stockQuantity: 55,
    storeSection: "meat",
    barcode: "1234567890132",
    nutritionInfo: {
      calories: 254,
      protein: 26,
      carbs: 0,
      fat: 16,
      fiber: 0,
      sodium: 75,
    },
    allergens: [],
    organic: false,
    glutenFree: true,
    vegan: false,
    vegetarian: false,
    weight: "1 lb",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_011",
    name: "Atlantic Salmon Fillet",
    price: 12.99,
    image: "🐟",
    category: "Seafood",
    subcategory: "Fish",
    brand: "Ocean Fresh",
    description: "Fresh Atlantic salmon fillet, rich in omega-3",
    tags: ["fresh", "omega-3", "protein", "heart-healthy"],
    rating: 4.7,
    reviewCount: 654,
    inStock: true,
    stockQuantity: 25,
    storeSection: "meat",
    barcode: "1234567890133",
    nutritionInfo: {
      calories: 206,
      protein: 22,
      carbs: 0,
      fat: 12,
      fiber: 0,
      sodium: 59,
    },
    allergens: ["fish"],
    organic: false,
    glutenFree: true,
    vegan: false,
    vegetarian: false,
    weight: "1 lb",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },

  // Bakery Section
  {
    id: "prod_012",
    name: "Whole Grain Bread",
    price: 3.49,
    image: "🍞",
    category: "Bakery",
    subcategory: "Bread",
    brand: "Dave's Killer Bread",
    description: "Organic whole grain bread with seeds and grains",
    tags: ["whole-grain", "organic", "fiber", "seeds"],
    rating: 4.5,
    reviewCount: 1567,
    inStock: true,
    stockQuantity: 85,
    storeSection: "deli",
    barcode: "1234567890134",
    nutritionInfo: {
      calories: 110,
      protein: 5,
      carbs: 22,
      fat: 2,
      fiber: 5,
      sodium: 170,
    },
    allergens: ["wheat", "soy"],
    organic: true,
    glutenFree: false,
    vegan: true,
    vegetarian: true,
    weight: "27 oz loaf",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_013",
    name: "Blueberry Muffins",
    price: 4.99,
    image: "🧁",
    category: "Bakery",
    subcategory: "Pastries",
    brand: "Bakery Fresh",
    description: "Fresh baked blueberry muffins with real blueberries",
    tags: ["fresh-baked", "blueberries", "breakfast", "sweet"],
    rating: 4.2,
    reviewCount: 432,
    inStock: true,
    stockQuantity: 35,
    storeSection: "deli",
    barcode: "1234567890135",
    nutritionInfo: {
      calories: 420,
      protein: 6,
      carbs: 65,
      fat: 16,
      fiber: 2,
      sodium: 380,
    },
    allergens: ["wheat", "eggs", "milk"],
    organic: false,
    glutenFree: false,
    vegan: false,
    vegetarian: true,
    weight: "4 pack",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },

  // Frozen Section
  {
    id: "prod_014",
    name: "Frozen Mixed Berries",
    price: 4.99,
    image: "🫐",
    category: "Frozen",
    subcategory: "Frozen Fruits",
    brand: "Nature's Best",
    description: "Frozen mix of strawberries, blueberries, and raspberries",
    tags: ["frozen", "antioxidants", "smoothies", "vitamin-c"],
    rating: 4.6,
    reviewCount: 789,
    inStock: true,
    stockQuantity: 95,
    storeSection: "frozen",
    barcode: "1234567890136",
    nutritionInfo: {
      calories: 70,
      protein: 1,
      carbs: 17,
      fat: 0.5,
      fiber: 5,
      sodium: 2,
    },
    allergens: [],
    organic: false,
    glutenFree: true,
    vegan: true,
    vegetarian: true,
    weight: "12 oz bag",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_015",
    name: "Vanilla Ice Cream",
    price: 5.49,
    image: "🍦",
    category: "Frozen",
    subcategory: "Ice Cream",
    brand: "Ben & Jerry's",
    description: "Premium vanilla ice cream made with real vanilla",
    tags: ["premium", "vanilla", "dessert", "creamy"],
    rating: 4.8,
    reviewCount: 2345,
    inStock: true,
    stockQuantity: 65,
    storeSection: "frozen",
    barcode: "1234567890137",
    nutritionInfo: {
      calories: 250,
      protein: 4,
      carbs: 23,
      fat: 16,
      fiber: 0,
      sodium: 50,
    },
    allergens: ["milk", "eggs"],
    organic: false,
    glutenFree: true,
    vegan: false,
    vegetarian: true,
    weight: "1 pint",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_016",
    name: "Frozen Pizza Margherita",
    price: 6.99,
    image: "🍕",
    category: "Frozen",
    subcategory: "Frozen Meals",
    brand: "DiGiorno",
    description: "Frozen pizza with mozzarella, tomato sauce, and basil",
    tags: ["frozen-meal", "pizza", "mozzarella", "convenient"],
    rating: 4.1,
    reviewCount: 1234,
    inStock: true,
    stockQuantity: 45,
    storeSection: "frozen",
    barcode: "1234567890138",
    nutritionInfo: {
      calories: 290,
      protein: 12,
      carbs: 36,
      fat: 11,
      fiber: 2,
      sodium: 700,
    },
    allergens: ["wheat", "milk"],
    organic: false,
    glutenFree: false,
    vegan: false,
    vegetarian: true,
    weight: "12 inch pizza",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },

  // Pantry Section
  {
    id: "prod_017",
    name: "Organic Pasta",
    price: 2.99,
    image: "🍝",
    category: "Pantry",
    subcategory: "Pasta",
    brand: "Barilla",
    description: "Organic whole wheat penne pasta",
    tags: ["organic", "whole-wheat", "pasta", "fiber"],
    rating: 4.4,
    reviewCount: 876,
    inStock: true,
    stockQuantity: 120,
    storeSection: "pantry",
    barcode: "1234567890139",
    nutritionInfo: {
      calories: 200,
      protein: 7,
      carbs: 42,
      fat: 1.5,
      fiber: 6,
      sodium: 0,
    },
    allergens: ["wheat"],
    organic: true,
    glutenFree: false,
    vegan: true,
    vegetarian: true,
    weight: "1 lb box",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_018",
    name: "Olive Oil Extra Virgin",
    price: 8.99,
    image: "🫒",
    category: "Pantry",
    subcategory: "Oils",
    brand: "Bertolli",
    description: "Cold-pressed extra virgin olive oil",
    tags: ["extra-virgin", "cold-pressed", "healthy-fats", "cooking"],
    rating: 4.7,
    reviewCount: 1456,
    inStock: true,
    stockQuantity: 75,
    storeSection: "pantry",
    barcode: "1234567890140",
    nutritionInfo: {
      calories: 120,
      protein: 0,
      carbs: 0,
      fat: 14,
      fiber: 0,
      sodium: 0,
    },
    allergens: [],
    organic: false,
    glutenFree: true,
    vegan: true,
    vegetarian: true,
    weight: "16.9 fl oz",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_019",
    name: "Quinoa",
    price: 5.99,
    image: "🌾",
    category: "Pantry",
    subcategory: "Grains",
    brand: "Ancient Harvest",
    description: "Organic tri-color quinoa, complete protein",
    tags: ["organic", "quinoa", "protein", "gluten-free"],
    rating: 4.5,
    reviewCount: 654,
    inStock: true,
    stockQuantity: 85,
    storeSection: "pantry",
    barcode: "1234567890141",
    nutritionInfo: {
      calories: 222,
      protein: 8,
      carbs: 39,
      fat: 4,
      fiber: 5,
      sodium: 13,
    },
    allergens: [],
    organic: true,
    glutenFree: true,
    vegan: true,
    vegetarian: true,
    weight: "1 lb bag",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_020",
    name: "Canned Black Beans",
    price: 1.49,
    image: "🫘",
    category: "Pantry",
    subcategory: "Canned Goods",
    brand: "Bush's Best",
    description: "Canned black beans, no added salt",
    tags: ["canned", "black-beans", "protein", "fiber"],
    rating: 4.3,
    reviewCount: 543,
    inStock: true,
    stockQuantity: 200,
    storeSection: "pantry",
    barcode: "1234567890142",
    nutritionInfo: {
      calories: 110,
      protein: 7,
      carbs: 20,
      fat: 0.5,
      fiber: 7,
      sodium: 460,
    },
    allergens: [],
    organic: false,
    glutenFree: true,
    vegan: true,
    vegetarian: true,
    weight: "15 oz can",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },

  // Snacks Section
  {
    id: "prod_021",
    name: "Almonds Raw",
    price: 7.99,
    image: "🥜",
    category: "Snacks",
    subcategory: "Nuts",
    brand: "Blue Diamond",
    description: "Raw almonds, heart-healthy snack",
    tags: ["raw", "almonds", "heart-healthy", "protein"],
    rating: 4.6,
    reviewCount: 987,
    inStock: true,
    stockQuantity: 95,
    storeSection: "snacks",
    barcode: "1234567890143",
    nutritionInfo: {
      calories: 160,
      protein: 6,
      carbs: 6,
      fat: 14,
      fiber: 4,
      sodium: 0,
    },
    allergens: ["tree nuts"],
    organic: false,
    glutenFree: true,
    vegan: true,
    vegetarian: true,
    weight: "1 lb bag",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_022",
    name: "Potato Chips",
    price: 3.99,
    image: "🥔",
    category: "Snacks",
    subcategory: "Chips",
    brand: "Lay's",
    description: "Classic potato chips, lightly salted",
    tags: ["chips", "potato", "snack", "crispy"],
    rating: 4.2,
    reviewCount: 1876,
    inStock: true,
    stockQuantity: 150,
    storeSection: "snacks",
    barcode: "1234567890144",
    nutritionInfo: {
      calories: 160,
      protein: 2,
      carbs: 15,
      fat: 10,
      fiber: 1,
      sodium: 170,
    },
    allergens: [],
    organic: false,
    glutenFree: true,
    vegan: true,
    vegetarian: true,
    weight: "8 oz bag",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },

  // Beverages
  {
    id: "prod_023",
    name: "Sparkling Water",
    price: 4.99,
    image: "💧",
    category: "Beverages",
    subcategory: "Water",
    brand: "LaCroix",
    description: "Natural sparkling water with lime flavor",
    tags: ["sparkling", "water", "lime", "zero-calories"],
    rating: 4.4,
    reviewCount: 1234,
    inStock: true,
    stockQuantity: 120,
    storeSection: "snacks",
    barcode: "1234567890145",
    nutritionInfo: {
      calories: 0,
      protein: 0,
      carbs: 0,
      fat: 0,
      fiber: 0,
      sodium: 0,
    },
    allergens: [],
    organic: false,
    glutenFree: true,
    vegan: true,
    vegetarian: true,
    weight: "12 pack cans",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_024",
    name: "Orange Juice",
    price: 3.99,
    image: "🍊",
    category: "Beverages",
    subcategory: "Juice",
    brand: "Tropicana",
    description: "100% pure orange juice, no pulp",
    tags: ["orange-juice", "vitamin-c", "no-pulp", "breakfast"],
    rating: 4.5,
    reviewCount: 876,
    inStock: true,
    stockQuantity: 85,
    storeSection: "snacks",
    barcode: "1234567890146",
    nutritionInfo: {
      calories: 110,
      protein: 2,
      carbs: 26,
      fat: 0,
      fiber: 0.5,
      sodium: 0,
    },
    allergens: [],
    organic: false,
    glutenFree: true,
    vegan: true,
    vegetarian: true,
    weight: "52 fl oz",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },

  // Household Items
  {
    id: "prod_025",
    name: "Paper Towels",
    price: 8.99,
    image: "🧻",
    category: "Household",
    subcategory: "Paper Products",
    brand: "Bounty",
    description: "Ultra-absorbent paper towels, 8 rolls",
    tags: ["paper-towels", "absorbent", "cleaning", "household"],
    rating: 4.7,
    reviewCount: 1567,
    inStock: true,
    stockQuantity: 75,
    storeSection: "household",
    barcode: "1234567890147",
    allergens: [],
    organic: false,
    glutenFree: true,
    vegan: true,
    vegetarian: true,
    weight: "8 rolls",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_026",
    name: "Laundry Detergent",
    price: 12.99,
    image: "🧴",
    category: "Household",
    subcategory: "Cleaning",
    brand: "Tide",
    description: "Liquid laundry detergent, fresh scent",
    tags: ["laundry", "detergent", "cleaning", "fresh-scent"],
    rating: 4.6,
    reviewCount: 2134,
    inStock: true,
    stockQuantity: 55,
    storeSection: "household",
    barcode: "1234567890148",
    allergens: [],
    organic: false,
    glutenFree: true,
    vegan: false,
    vegetarian: true,
    weight: "100 fl oz",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_027",
    name: "Toilet Paper",
    price: 8.59,
    image: "🧻",
    category: "Household",
    subcategory: "Paper Products",
    brand: "Charmin",
    description: "Ultra soft toilet paper, 12 mega rolls",
    tags: ["toilet-paper", "soft", "mega-rolls", "household"],
    rating: 4.8,
    reviewCount: 3456,
    inStock: true,
    stockQuantity: 95,
    storeSection: "household",
    barcode: "1234567890149",
    allergens: [],
    organic: false,
    glutenFree: true,
    vegan: true,
    vegetarian: true,
    weight: "12 mega rolls",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "prod_028",
    name: "Dish Soap",
    price: 3.99,
    image: "🧽",
    category: "Household",
    subcategory: "Cleaning",
    brand: "Dawn",
    description: "Ultra concentrated dish soap, cuts grease",
    tags: ["dish-soap", "concentrated", "grease-cutting", "cleaning"],
    rating: 4.5,
    reviewCount: 1876,
    inStock: true,
    stockQuantity: 125,
    storeSection: "household",
    barcode: "1234567890150",
    allergens: [],
    organic: false,
    glutenFree: true,
    vegan: false,
    vegetarian: true,
    weight: "24 fl oz",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
]

// Helper functions for product operations
export function getProductById(id: string): Product | undefined {
  return PRODUCTS_DATABASE.find((product) => product.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  return PRODUCTS_DATABASE.filter((product) => product.category.toLowerCase() === category.toLowerCase())
}

export function getProductsByStoreSection(section: string): Product[] {
  return PRODUCTS_DATABASE.filter((product) => product.storeSection.toLowerCase() === section.toLowerCase())
}

export function searchProducts(query: string): Product[] {
  const searchTerm = query.toLowerCase()
  return PRODUCTS_DATABASE.filter(
    (product) =>
      product.name.toLowerCase().includes(searchTerm) ||
      product.description.toLowerCase().includes(searchTerm) ||
      product.tags.some((tag) => tag.toLowerCase().includes(searchTerm)) ||
      product.brand.toLowerCase().includes(searchTerm) ||
      product.category.toLowerCase().includes(searchTerm),
  )
}

export function getProductsByPriceRange(minPrice: number, maxPrice: number): Product[] {
  return PRODUCTS_DATABASE.filter((product) => product.price >= minPrice && product.price <= maxPrice)
}

export function getProductsByDietaryRestrictions(restrictions: string[]): Product[] {
  return PRODUCTS_DATABASE.filter((product) => {
    return restrictions.every((restriction) => {
      switch (restriction.toLowerCase()) {
        case "organic":
          return product.organic === true
        case "gluten-free":
          return product.glutenFree === true
        case "vegan":
          return product.vegan === true
        case "vegetarian":
          return product.vegetarian === true
        default:
          return true
      }
    })
  })
}

export function getFeaturedProducts(limit = 10): Product[] {
  return PRODUCTS_DATABASE.filter((product) => product.rating >= 4.5)
    .sort((a, b) => b.reviewCount - a.reviewCount)
    .slice(0, limit)
}

export function getTopRatedProducts(limit = 10): Product[] {
  return PRODUCTS_DATABASE.sort((a, b) => b.rating - a.rating).slice(0, limit)
}

export function getProductsOnSale(): Product[] {
  return PRODUCTS_DATABASE.filter((product) => product.originalPrice && product.originalPrice > product.price)
}

export function getProductsByBrand(brand: string): Product[] {
  return PRODUCTS_DATABASE.filter((product) => product.brand.toLowerCase() === brand.toLowerCase())
}

export function getAllCategories(): string[] {
  return [...new Set(PRODUCTS_DATABASE.map((product) => product.category))]
}

export function getAllBrands(): string[] {
  return [...new Set(PRODUCTS_DATABASE.map((product) => product.brand))]
}

export function getProductRecommendations(productId: string, limit = 5): Product[] {
  const product = getProductById(productId)
  if (!product) return []

  // Get products from same category with similar tags
  return PRODUCTS_DATABASE.filter(
    (p) => p.id !== productId && (p.category === product.category || p.tags.some((tag) => product.tags.includes(tag))),
  )
    .sort((a, b) => b.rating - a.rating)
    .slice(0, limit)
}
